- hosts: gitlab
  become: yes
  roles:
    - { role: Gitlab }

- hosts: production
  become: yes
  roles:
    - { role: Production }

- hosts: monitoring
  become: yes
  roles:
    - { role: Monitoring }

- hosts: gitlab, production
  become: yes
  roles:
    - { role: Promtail }

